### ISSUE TITLE
No protection from adding new characters from the outside

### ISSUE THREAD

**Issue by juliaProjorlivy** [R0flan4k/Stack#1]
**Expected behaviour:** should have detected invasion into data, should print error text, `error_code` should be assigned as an error value
**Real behaviour:** works as if there is no data change from the outside, returns `error_code` as a zero
**Steps to reproduce:** make protection of the data
1) create stack
2) push some values using `stack_push` 
3) change the value in stack, e.g. `stk.data[stk.size + 3] = 888;` 
4) destruct the stack 
5) check `error_code`

Version: commit 22196a4

**Comment by R0flan4k** [comment]
Hello, juliaProjorlivy!

Thanks for your review. This problem was fixed by commit [6dbc620](https://github.com/R0flan4k/Stack/commit/6dbc62013558764d35414ea1516966068614fc77).

With best regards, R0flan4k.
