### ISSUE TITLE
Memory violation in stack

### ISSUE THREAD

**Issue by juliaProjorlivy** [R0flan4k/Stack#2]
**Expected behaviour:** `ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)`
**Real behaviour:** `Invalid write of size 8 at 0x109D3D: stack_expand_memory(Stack*) (stack.cpp:173)`
**Steps to reproduce:** push untill resize
Version: commit 22196a4

**Comment by R0flan4k** [comment]
Hi, juliaProjorlivy!

Thanks for your review. I fixed this problem by commit [6dbc620](https://github.com/R0flan4k/Stack/commit/6dbc62013558764d35414ea1516966068614fc77).

With best regards, R0flan4k.
