### ISSUE TITLE
Incorrect behaviour

### ISSUE THREAD

**Issue by KetchuppOfficial** [R0flan4k/Stack#3]
Hi, R0flan4k!

First of all, if your program requires something more complex than running **make** with no options to be built, you should document it in README.

Second of all, if a functions receives a pointer and it is dereferenced somewhere in the function body, you really should handle the case of the pointer being NULL. For example, a program that uses your stack and has the following main function crashes with segmentation fault.

![image](https://github.com/R0flan4k/Stack/assets/83651035/a7fb8204-2aec-4b19-b311-675761434fda)
![image](https://github.com/R0flan4k/Stack/assets/83651035/966d59a1-5f92-4ed5-8ed5-719aa0b29a1d)

I hope you'll fix all mentioned problems soon.

With best regards, KetchuppOfficial

**Comment by R0flan4k** [comment]
Hello, KetchuppOfficial!

Thank you for your issue. All problems that you listed was solved in commit [15f9004](https://github.com/R0flan4k/Stack/commit/15f90048c0c2ddac5de8c3bd1add0a51fb276f85).

Respectfully, R0flan4k.
