### ISSUE TITLE
Make still refuses to build

### ISSUE THREAD

**Issue by KetchuppOfficial** [R0flan4k/Stack#4]
Hi, R0flan4k!

You still have some problems with the build system. Namely, following steps described in README leads to an error from **make**.

![image](https://github.com/R0flan4k/Stack/assets/83651035/807bf022-5b75-4158-97bb-5d18871020b5)

The problem is that you have **MakeFile** not **Makefile** in */src*. This way you should run **make** as follows:
```bash
make -f MakeFile
```

Hope you'll rename makefile or fix README soon.

With best regards, KetchuppOfficial

**Comment by R0flan4k** [comment]
Hello, KetchupOfficial!

Thank you for your review! This problem was solved in commit [fe5a52b](https://github.com/R0flan4k/Stack/commit/fe5a52bd5a7364805e5f92bad83ee0301bf50aab).

Respectfully, R0flan4k.
