### ISSUE TITLE
Yet another segmentation fault

### ISSUE THREAD

**Issue by KetchuppOfficial** [R0flan4k/Stack#5]
Hi, R0flan4k!

I succeeded in crushing your stack with segmentation fault again.
```C
#include <stdlib.h>

#include "stack.h"

int main (void)
{
    Stack stk = {};

    stack_ctor(&stk);
    stack_push(&stk, 4);

    stk.data = NULL;

    stack_dtor(&stk);

    return 0;
}
```

![image](https://github.com/R0flan4k/Stack/assets/83651035/68b4be85-055a-4803-ba67-668c840631c8)

Hope you'll fix the probem despite general physics :)

With best regards, KetchuppOfficial

**Comment by R0flan4k** [comment]
Hello, KetchupOfficial!

Thanks for your review. This problem was caused by stack_dtor() incorrectly working. 
I fixed this problem in commit [6dbc620](https://github.com/R0flan4k/Stack/commit/6dbc62013558764d35414ea1516966068614fc77).

Respectfully, R0flan4k.
